Data analytics

In [6]:
import pandas as pd #runs production code

# from pandas import Series, DataFrame 





row_of_data = [10,20,30,40]
cols = ['siren', 'marlo', 'kendall', 'mom']
series_of_data = pd.Series(row_of_data)
print(f'list: {row_of_data}')
print(f'series: \n{series_of_data}')

list: [10, 20, 30, 40]
series:
0    10
1    20
2    30
3    40
dtype: int64

In [8]:
#DataFrame by column

family = {
    "name": ["syd", "olivia", 'kendall', 'lauren'],
    "age": [20,30,10,50],
}

df1 = pd.DataFrame(data = family, index= family["name"])
df1

# series_of_data.mean()

            name  age
syd          syd   20
olivia    olivia   30
kendall  kendall   10
lauren    lauren   50

In [10]:
# DataFrame by rows

cols1 = ['name','age']
rows = [
    ['syd',20],
    ['kendall',16],
    ['siren',5],
    ['marlo',4],
]

df2 = pd.DataFrame(data=rows, columns=cols1)
df2

      name  age
0      syd   20
1  kendall   16
2    siren    5
3    marlo    4

In [15]:
df1['age']['syd']

np.int64(20)

In [16]:
df2['name'][1]

'kendall'

In [17]:
df2['gender'] = ['f','m','f','f']
df2

      name  age gender
0      syd   20      f
1  kendall   16      m
2    siren    5      f
3    marlo    4      f

In [18]:
df2[['name', 'gender']]

      name gender
0      syd      f
1  kendall      m
2    siren      f
3    marlo      f

In [19]:
df2.columns

Index(['name', 'age', 'gender'], dtype='str')

In [21]:
df2.head(2)

      name  age gender
0      syd   20      f
1  kendall   16      m

In [ ]:
df2.isnull().sum()

name      0.0
age       0.0
gender    0.0
dtype: float64

In [25]:
df2.describe()

             age
count   4.000000
mean   11.250000
std     7.973916
min     4.000000
25%     4.750000
50%    10.500000
75%    17.000000
max    20.000000

In [ ]:
df1.sort_index(ascending=False, inplace=True)

            name  age
syd          syd   20
olivia    olivia   30
lauren    lauren   50
kendall  kendall   10

In [30]:
df1 = df1.sort_values(['age'])
df1

            name  age
kendall  kendall   10
syd          syd   20
olivia    olivia   30
lauren    lauren   50

In [31]:
df2 = df2.rename(columns={'age': 'a'})
df2

      name   a gender
0      syd  20      f
1  kendall  16      m
2    siren   5      f
3    marlo   4      f

In [ ]:
df2.loc[0]

name      syd
a          20
gender      f
Name: 0, dtype: object

In [34]:
df2.loc[0, 'a']

np.int64(20)

In [36]:
df2.loc[0, 'a'] = 21
df2

      name   a gender
0      syd  21      f
1  kendall  16      m
2    siren   5      f
3    marlo   4      f

In [41]:
df1.iloc[0,1]

np.int64(10)

In [43]:
df1 = df1.reset_index()
df1

     index     name  age
0  kendall  kendall   10
1      syd      syd   20
2   olivia   olivia   30
3   lauren   lauren   50

In [46]:
df1.drop(labels = ['index'], axis='columns')

      name  age
0  kendall   10
1      syd   20
2   olivia   30
3   lauren   50

In [47]:
df2.at[0, 'a']

np.int64(21)

In [48]:
df2.iat[1,1] = 39
df2

      name   a gender
0      syd  21      f
1  kendall  39      m
2    siren   5      f
3    marlo   4      f

In [49]:
df2.loc[0:3, 'name']

0        syd
1    kendall
2      siren
3      marlo
Name: name, dtype: str

In [50]:
df2.loc[df2['a'] >18]

      name   a gender
0      syd  21      f
1  kendall  39      m

In [51]:
df2.loc[df2['a'] >18, 'name']

0        syd
1    kendall
Name: name, dtype: str

In [52]:
df2['is_adult'] = False
df2

      name   a gender  is_adult
0      syd  21      f     False
1  kendall  39      m     False
2    siren   5      f     False
3    marlo   4      f     False

In [53]:
df2.loc[df2['a'] >= 18, 'is_adult'] = True
df2

      name   a gender  is_adult
0      syd  21      f      True
1  kendall  39      m      True
2    siren   5      f     False
3    marlo   4      f     False

In [ ]:
df2.to_csv('')