- loops
- rename data 
- apply
- aggregate data

In [ ]:
import pandas as pd 

#data = 'https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv'
# urls are just a series of files
#df = pd .read_csv(data)
#df .head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [ ]:
# ./filename.csv-  call a path at current folder.filename.csv
# ../ => goes back one folder
#df.to_csv("../data/french-ambs.csv", index=False)

In [5]:
df = pd.read_csv("../data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [ ]:
df = df.drop(columns=['lat_long']) # .drop exist on a dataframe
df.head()

   id                name    place  year    lat   long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57

In [8]:

df = df[['name', 'place', 'year']]
df.head()

                 name    place  year
0  Richer, Christophe  Denmark  1543
1  Richer, Christophe  Denmark  1541
2  Danzay, Charles de  Denmark  1561
3  Danzay, Charles de  Denmark  1563
4  Danzay, Charles de  Denmark  1582

In [9]:
df['place'].unique()

<StringArray>
[          'Denmark',           'England',            'Geneva',
           'Grisons', 'Holy Roman Empire',       'Netherlands',
    'Ottoman Empire',          'Portugal',              'Rome',
          'Scotland',             'Spain',     'Swiss Cantons',
            'Venice',            'Poland',             'Savoy',
           'Ferrara',            'Saxony',           'Tuscany']
Length: 18, dtype: str

In [ ]:
df['place'].count()
df['place'].astype

18

In [16]:
# Loops
#iterrows / itertuples
#iterrows
for idx, row in df.iterrows():
    if row['place'] == 'Holy Roman Empire':
        df.at[idx, 'place'] = 'HRE'
        
df['place'].unique()

<StringArray>
[       'Denmark',        'England',         'Geneva',        'Grisons',
            'HRE',    'Netherlands', 'Ottoman Empire',       'Portugal',
           'Rome',       'Scotland',          'Spain',  'Swiss Cantons',
         'Venice',         'Poland',          'Savoy',        'Ferrara',
         'Saxony',        'Tuscany']
Length: 18, dtype: str

In [21]:
for row in df.itertuples():
    idx = row.Index
    if row.place == "Ottoman Empire":
        df.at[idx,'place'] = "Ott"
        
df['place'].unique()

<StringArray>
[      'Denmark',       'England',        'Geneva',       'Grisons',
           'HRE',   'Netherlands',           'Ott',      'Portugal',
          'Rome',      'Scotland',         'Spain', 'Swiss Cantons',
        'Venice',        'Poland',         'Savoy',       'Ferrara',
        'Saxony',       'Tuscany']
Length: 18, dtype: str

In [26]:
# using .loc to replace
df.loc[df['place'] == 'Netherlands', 'place'] = 'Neth'
df['place'].unique()

<StringArray>
[      'Denmark',       'England',        'Geneva',       'Grisons',
           'HRE',          'Neth',           'Ott',      'Portugal',
          'Rome',      'Scotland',         'Spain', 'Swiss Cantons',
        'Venice',        'Poland',         'Savoy',       'Ferrara',
        'Saxony',       'Tuscany']
Length: 18, dtype: str

In [27]:
#hash is dict
# replace many with a hash using .replace
hash = {place: f'{place[:3] + '.' if len(place) > 4 else place}' for place in df['place'].unique()}
df['place'] = df['place'].replace(hash)
df['place'].unique()

<StringArray>
['Den.', 'Eng.', 'Gen.', 'Gri.',  'HRE', 'Neth',  'Ott', 'Por.', 'Rome',
 'Sco.', 'Spa.', 'Swi.', 'Ven.', 'Pol.', 'Sav.', 'Fer.', 'Sax.', 'Tus.']
Length: 18, dtype: str

In [24]:
# complex boolean logic with | (or), & (and), ~ (not)
df.loc[((df['place'] == 'Netherlands') | (df['place'] == 'England')) & (df['year'] <1550)]

                                name        place  year
5                 Bapaume, Robert de      England  1516
6           Passano, Jean-Joachim de      England  1527
7                        De Monpreat      England  1532
8                    Du Bellay, Jean      England  1530
9              Castelnau, Antoine de      England  1534
10                    De Selve, Odet      England  1547
116              Dinteville, Jean de      England  1536
158  Gouffier de Bonnivet, Guillaume      England  1518
159         Passano, Jean-Joachim de      England  1525
253             Marillac, Charles de      England  1543
262               Hellin, Antoine de  Netherlands  1538
263               Hellin, Antoine de  Netherlands  1539
365              Dinteville, Jean de      England  1533
366                Du Perreau, Louis      England  1538
367                   De Selve, Odet      England  1546
369                Du Perreau, Louis      England  1539
381          La Pommeraie, Gilles de  Netherlands  1529
382               Hellin, Antoine de  Netherlands  1540
383                    Crotto, Livio  Netherlands  1547
486                Du Perreau, Louis      England  1533
535                  Du Bellay, Jean      England  1528
536          La Pommeraie, Gilles de      England  1532
537            Castelnau, Antoine de      England  1535
593         Passano, Jean-Joachim de      England  1526
594                  Du Bellay, Jean      England  1529
595             Marillac, Charles de      England  1542
597              Dinteville, Jean de      England  1537
598            Castelnau, Antoine de      England  1536
639                Du Perreau, Louis      England  1534
640                Du Perreau, Louis      England  1537
641             Marillac, Charles de      England  1540
656          La Pommeraie, Gilles de  Netherlands  1530
705                  Du Bellay, Jean      England  1527
706             Marillac, Charles de      England  1541
707             Marillac, Charles de      England  1539
719                    Crotto, Livio  Netherlands  1546
817          La Pommeraie, Gilles de      England  1531
819                   De Selve, Odet      England  1548

In [29]:
df.loc[~((df['place'] == 'Netherlands')) & (df['year'] >1588) & (df['year'] <1592)]

                              name place  year
114                 Hurault, André  Ven.  1591
130               Ancel, Guillaume   HRE  1590
137    Lancosme, Jacques Savary de   Ott  1590
162       L'Aubspine, Guillaume de  Eng.  1589
223               Ancel, Guillaume   HRE  1591
304              Hurault, François  Ven.  1589
307             Danzay, Charles de  Den.  1589
352            Brûlart, Nicolas de  Swi.  1591
371                La Fin, Jean de  Eng.  1590
415            Brûlart, Nicolas de  Swi.  1589
481                 Hurault, André  Ven.  1590
530            Brûlart, Nicolas de  Swi.  1590
532                 Hurault, André  Ven.  1589
622  Longlée, Pierre de Seguson de  Spa.  1589
720               Ancel, Guillaume   HRE  1589
727    Lancosme, Jacques Savary de   Ott  1591
736               Vivonne, Jean de  Rome  1589
767       L'Aubspine, Guillaume de  Eng.  1590
768                La Fin, Jean de  Eng.  1591
788    Lancosme, Jacques Savary de   Ott  1589
789     De Brèves, François Savary   Ott  1591

In [ ]:
# .apply() takes a function